### ISSUE TITLE
Is Timeslider an option for ownCloud documents?

### ISSUE THREAD

**Issue by dmkscr** [owncloud/documents#111]
To enhance the thinking of collaborative work in ownCloud documents is a timeslider (e.g. Etherpad) an option for ownCloud?

http://pad.merz-akademie.de/ep/pad/view/owncloudtimeslider/latest

![xxxxx](https://f.cloud.github.com/assets/5917507/1520721/c0534252-4b81-11e3-90dc-d93a4024932a.JPG)

**Comment by jancborchardt** [comment]
Closing this because it is a tad overkill. I rarely found myself using this when using Etherpad. A better way are simple versions which we already support.
