### ISSUE TITLE
chat available while editing?

### ISSUE THREAD

**Issue by liska12** [owncloud/documents#137]
Hi,
I've tried simultaneous edit of documents and it is great and I can see a huge benefits for my organization. 
But what am I missing now is a chat application. It'd be much better if I could have  conversation with my coworkers while editing common document. 
I haven't found anything on this topic yet on this list.

Thanks a lot for your excelent work.

**Comment by LEDfan** [comment]
@VicDeo @jancborchardt @menelic I'm working on this :) Ref this PR: https://github.com/owncloud/chat/pull/191 .

Some screenshots:
![schermafbeelding 2015-02-13 op 11 18 31](https://cloud.githubusercontent.com/assets/2996275/6185720/146765a4-b372-11e4-9abd-23bf4dcf4b2e.png)
![schermafbeelding 2015-02-13 op 11 18 36](https://cloud.githubusercontent.com/assets/2996275/6185721/15754c4a-b372-11e4-8246-d1f50406dc13.png)
This is an early implementation, it has to be styled more :)
Currently it overlaps the avatar sidebar, there are some options:
1. move the chat bar 70px from the right to the left, so the avatar bar is between the chat bar and the side of your screen:
![schermafbeelding 2015-02-13 op 11 22 22](https://cloud.githubusercontent.com/assets/2996275/6185767/986edbc0-b372-11e4-9465-8cf23ccf9fb7.png)
2. move the avatar bar to the left side of the chat bar:
![schermafbeelding 2015-02-13 op 11 25 10](https://cloud.githubusercontent.com/assets/2996275/6185803/fc1ae722-b372-11e4-9f75-2d35dd71cd74.png)

**Comment by cmonteroluque** [comment]
@LEDfan thank you for the PR for the first implementation! Do you have an update on your PR?

**Comment by jancborchardt** [comment]
cc @sualko @LEDfan I guess the new Chat app will integrate similarly nice into every app by default anyway, right?

**Comment by sualko** [comment]
It does already.

**Comment by jancborchardt** [comment]
:=

**Comment by jancborchardt** [comment]
:)
