### ISSUE TITLE
Copy-paste broken in OC6 RC2

### ISSUE THREAD

**Issue by PVince81** [owncloud/documents#151]
### Steps
1. Write some text
2. Select the text with the keyboard (Shift + arrows) or with the mouse
3. Hit Ctrl+C
4. Move to a different position
5. Hit Ctrl+V
### Actual result

Nothing pasted
### Expected result

The text copied at step 3 is pasted at step 5
### Versions

ownCloud 6 RC 2 on openSUSE 12.3
Browser: Firefox 25

**Comment by tony5** [comment]
I think this bug may still exist.
I can copy and paste with Hit Ctrl+V in chromium but not with firefox
