### ISSUE TITLE
Implement WebODFs rich annotation feature in owncloud Documents

### ISSUE THREAD

**Issue by menelic** [owncloud/documents#177]
WebODF already contains rich annotations, which are one of the few useability advantages Google Docs still has over oC Documents. They are also key for meaningful collaboration, which is a core aim of oC Documents. The rich annotation feature should be implemented in oC - with the ability to respond to comments with other comments threaded underneath the first one, as in Google Docs.

Exosting WebODF implementation:

![f666c30c-6736-11e3-840d-29a9c75ce998 1](https://f.cloud.github.com/assets/5934115/1765600/1af7df02-6738-11e3-985d-acae57e9c6e3.JPG)

**Comment by jdhoek** [comment]
The current document editing functionality in ownCloud 7 is quite close to being a viable alternative for collaborative of documents in Google Drive. For me comments are the most desired functionality missing now. Is this issue on the roadmap?

**Comment by VicDeo** [comment]
Implemented for 0.5.7
