### ISSUE TITLE
Sharing a file though "files" automatically makes it editable in "documents"

### ISSUE THREAD

**Issue by tribut** [owncloud/documents#232]
When files are shared through the "files" app, a link like `https://host.tld/public.php?service=files&t=token` is generated. The user does not expect this to grant write permission to those files and generally, it doesn't. When `.odt` files are shared however, anyone can simply replace `service=files` with `service=documents` and edit the file.

I believe this is non-obvious and a security-critical design flaw. A different token should be used for apps that grant write permission.

**Comment by jancborchardt** [comment]
Closing this in favor of https://github.com/owncloud/documents/issues/581 because we have more up-to-date discussion there. Let’s continue there :)
