### ISSUE TITLE
[7.0 beta 1] What about .doc and .docx files? Don´t work.

### ISSUE THREAD

**Issue by enoch85** [owncloud/documents#291]
Just spent like 3 hours trying to get .docx and .doc files to work. I have installed LibreOffice 4.2 on my Ubuntu Server 12.04 and made the correct changes according to the documentation, setting 'preview_libreoffice_path' => '/usr/bin/libreoffice/', in config.php, and I also tried without that line.
### Owncloud.log:

---

Warning  documents   Starting a session failed. Reason: Empty conversion output  2014-06-28T16:35:44+00:00
Warning  documents   Empty conversion output     2014-06-28T16:35:44+00:00
Error    PHP     file_get_contents(/tmp/7896d1c467daf2046f0f1a920c8d45fb//5b376c6997adc7e36becf2ed5f949db2.odt): failed to open stream: No such file or directory at /var/www/owncloud/apps/documents/lib/converter.php#56   2014-06-28T16:35:44+00:00
Warning documents   Starting a session failed. Reason: Empty conversion output

---

I have tried to search for an external solution regarding the file-format-server to see if it had something to do with my install of LibreOffice but I didn´t find any. As you already know it says http://localhost:16080 in the admin settings as an external address, and just to confirm: that address has no function at all, right? And I also wonder if you guys know any server I can use for that purpose? Don´t think I should need it though as I have a fresh install och both LibreOffice 4.2 and oC 7 beta 1, right? Anyway, I can see previews from both .doc and .docx so my LibreOffice install should work.

Another thing I saw when I Googled for soulutions was this: https://github.com/owncloud/format-filter-server What is this? Are you planning on writing your own filter-server? In that case it means that .doc and .docx isn´t supported fully yet, or am I wrong?

When I try to open a docx or doc document in Web UI I usually get two errors, one or the other, plus the log of course.
1. "Failed to load this document. Please check if it can be opened with an external odt editor. This might also mean it has been unshared or deleted recently."

![namnls](https://cloud.githubusercontent.com/assets/4511254/3421311/29f442d0-fee5-11e3-94d5-72d8753a03bf.png)

And I have also seen a bunch of these: 
1. Format filter server is down or misconfigured (Can I install a Format-filter-server in Ubuntu or is that the function that LibreOffice gets me?)

Many questions, I hope I (and other users) can get some answers soon. 
### Expected behavior

No problems, issues, or glitches with the documents app regarding .doc and .docx
### Actual behavior

Can´t open Office documents at all. I can see the previews though.
### Server configuration

Ubuntu Server 12.04 (latest updates)
oC 7 Beta 1
MySQL & PHP (latest updates)
### Browser

Chrome (latest)
I also tried with IE, same thing there.

**Comment by denysvitali** [comment]
Had a similar problem.
That was caused by a directive of php.ini (php_admin_value of apache in my case) which excluded some functions, particularly `shell_exec, escapeshellcmd, escapeshellarg, exec`

Obviously fixed by removing them.
Just sharing here because I've lost too much time finding out and testing what was the problem. Hope it could help someone!

**Comment by RealRancor** [comment]
@denysvitali 
Yepp, those are needed to get LibreOffice to work but are not really documented anywhere. :-/

I had reported this some weeks ago at https://github.com/owncloud/core/issues/14092

**Comment by danielberlin** [comment]
Only `escapeshellarg` and `shell_exec`, there are other prerequisites though: https://doc.owncloud.org/server/7.0/admin_manual/configuration/collaborative_documents_configuration.html
