### ISSUE TITLE
"Conversion failed. Check log for details." when testing the LO preview in admin

### ISSUE THREAD

**Issue by ghost** [owncloud/documents#341]
### Steps to reproduce
1. Configure libreoffice according to doc.owncloud.org and our FAQ at the forums: https://forum.owncloud.org/viewtopic.php?f=17&t=22948
2. Open admin backend
3. Use "Local" option and click on "apply and test"
### Expected behaviour

The test for LibreOffice should work as expected or at least a meaningful message should be shown in the logfile to debug this.
### Actual behaviour

A red box showing "Conversion failed. Check log for details." appears.
### Server configuration

**Operating system**: Debian wheezy

**Web server:** NginX 1.6.x

**Database:** MariaDB 10.0.x

**PHP version:** 5.5.x

**ownCloud version:** 7.0.1

**Updated from an older ownCloud or fresh install:** Updated from OC6

**List of activated apps:** Default apps + mozilla_sync

**The content of config/config.php:**

```
<?php

define("DEBUG", true);

$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.1.1',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_smtpmode' => 'php',
  'trusted_domains' =>
  array (
    0 => 'example.com',
  ),
  'loglevel' => '0',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no
### Client configuration

**Browser:** Firefox 31

**Operating system:** Windows 8.1
#### Web server access log

```
127.0.0.1 - - [17/Aug/2014:21:21:08 +0200] "POST /index.php/apps/documents/ajax/admin.php HTTP/1.1" 200 81 "https://example.com/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0"
```
#### ownCloud log (data/owncloud.log)

```
{"reqId":"53f100a41a84a","app":"documents","message":"Conversion failed. Raw output:","level":2,"time":"2014-08-17T19:21:08+00:00","method":"POST","url":"\/index.php\/apps\/documents\/ajax\/admin.php"}
```
#### Browser log

```
https://example.com/index.php/apps/documents/ajax/admin.php?converter=local

{"data":{"message":"Conversion failed. Check log for details."},"status":"error"}
```

**Comment by bugsyb** [comment]
RealRancor recommendation worked for me.
