### ISSUE TITLE
UI for document editing looks weird and docs cannot be edited when asset-pipeline is enabled

### ISSUE THREAD

**Issue by stonerl** [owncloud/documents#348]
![screen shot 2014-08-28 at 10 58 28](https://cloud.githubusercontent.com/assets/2091312/4073214/da9c8184-2e91-11e4-8901-7503de22580f.png)

owncloud 7.0.2 on ubuntu 14.04 Server
Firefox 31 & Opera 23 on OS X 10.9.4

**Comment by Temtaime** [comment]
[http://a-rei.ru/yC_I](url)
I have a same probem with owncloud 9.1.3 and pipeline enabled.
Owncloud generates empty .css file.
