### ISSUE TITLE
[OC 7.0.2] Office conversion fails when more than one instance of OC is installed on a single server

### ISSUE THREAD

**Issue by oparoz** [owncloud/documents#352]
### Setup
1. Install LibreOffice
2. Install 2 instances of OC 7 on a server, using 2 different unix users (user1 and user2)
3. Change their configuration so that they both use the installed libreoffice binary
4. Using instance1, upload a .doc document and try to edit it
5. Look at the server's temporary folder (usually /tmp), you should see a folder called "user" owned by user1
6. Using instance2, upload a .doc document and try to edit it

### Expected behavior
You should be able to edit the document

### Actual behavior
The conversion fails

### Tests
You can chmod /tmp/user to 777 or delete that folder and users on instance2 of OC will then be able to convert documents.

### Solutions
This commit could be modified so that the config path includes a folder named after the domain used per example
https://github.com/owncloud/documents/commit/fb85b0f26293844515f696008f62284c41180a93

EDIT: I'm proposing this: #353

### Server configuration
FreeBSD 9
Temporary folder is /tmp

**Comment by VicDeo** [comment]
Fixed https://github.com/owncloud/documents/pull/474
