### ISSUE TITLE
Documents App does not load with very many documents

### ISSUE THREAD

**Issue by rasos** [owncloud/documents#369]
The Documents App works fine if a user has access only to a few documents, including editing. However, it loads endlessly, showing opExecutionFailure or a Javascript error, if a user has access to thousands of documents.
![bildschirmfoto vom 2014-10-02 15 23 45](https://cloud.githubusercontent.com/assets/485723/4491297/6e452268-4a37-11e4-93e0-62a496c1cfaf.png)
When clicking on a document server seems still busy:
![bildschirmfoto vom 2014-10-02 11 34 28](https://cloud.githubusercontent.com/assets/485723/4491167/d1d76162-4a35-11e4-8661-58ff74484da2.png)
It is not possible anymore to navigate to "Files" or another App. Users need to close the browser window.

Environment: OC7.02, Ubuntu 12.04 VM with 4GB RAM, data on NFS
tested with Chrome and Firefox

**Comment by VicDeo** [comment]
Closing as resolved
