### ISSUE TITLE
document preview

### ISSUE THREAD

**Issue by tony5** [owncloud/documents#385]
I am using  freebsd 10.0 with apache, PHP Version 5.6.1 and ownCloud 7.0.2 (stable) 

I am having trouble with image previews. 

Pdf, txt, and images work.

Odt files will not display a thumbnail.

I see this error in  httpd-error.log

Warning: -convert-to is deprecated.  Use --convert-to instead.
Warning: -outdir is deprecated.  Use --outdir instead.
:1: parser error : Document is empty

in owncloud log I see,

Error 
core 
Unable to read the file: /tmp/0405359c5f46d63d89749e716e2a6816ods.pdf[0] 

I hope that is enough information

take care.

**Comment by VicDeo** [comment]
Fix is merged into the core. Feel free to reopen if the issue persists with more recent OC 7 or 8 releases.
