### ISSUE TITLE
Editing is only available in Document App and not in Files

### ISSUE THREAD

**Issue by donniezazen** [owncloud/documents#424]
In the web interface, documents are only available to be edited when uploaded and accessed through the Document App. Any documents accessed via files are only available for preview. Document in Documents App aren't even synced with the desktop client.

Document editing should be supported across the ownCloud account and it shouldn't be only for documents submitted to the Document App.

I am using ownCloud 7.0.4 on CentOS 7 via OBS. I tested the above problem with an odt file. No LibreOffice is installed on the server.

**Comment by karlitschek** [comment]
@VicDeo Can you have a look?

**Comment by wakeup** [comment]
@donniezazen if you have documents app enabled, you can click on Edit in Files list to edit. By default, if you click on the name it wil be opened with viewer which is intended:

![image](https://cloud.githubusercontent.com/assets/231068/5705524/3b3cd18e-9a7a-11e4-888a-2ee86fa87960.png)

**Comment by donniezazen** [comment]
@wakeup Thanks. That makes sense. Some of sort of information on First Run or Tool Tips would be very helpful.

Initially Document Apps behaved like a dead end where if you create a document it wouldn't get synced but I am not able to reproduce it anymore. Glad there is no problem.
