### ISSUE TITLE
thousands of 404s causing server to hang on load of documents screen.

### ISSUE THREAD

**Issue by datapharmer** [owncloud/documents#425]
I have a large number of documents on the server, but even with enable_previews set to false (which shouldn't matter with the latest release) I have logs registering thousands of 404s for https://owncloud.mydomain.com/index.php/core/preview.png?file=%Directory%2File.docx&x=220.00000476837158&y=220.00000476837158&c=54a31ded3a095&forceIcon=0 This causes the documents section to hang for several minuts on load and in some cases the server gets overwhelmed and starts throwing 500s for a while. Also, if you don't wait several minutes for the generic thumbnails to appear and click new document (assuming there are no existing documents), it will not ever load the editor. Waiting for a few minutes for generic thumbnails to appear and then click and it will work.

**Comment by DeepDiver1975** [comment]
@datapharmer Which OC version are you using? THX

@VicDeo can you please have a look? THX

**Comment by datapharmer** [comment]
@DeepDiver1975 7.0.4-3 from the opensuse repository for xubuntu_14.04.  I think the issue is since we have many documents when the thumbnails try to load for too many it overwhelms the server. The 404s are because of no thumbs being generated for documents with our current config (which is to generate thumbs only for owncloud's default filetypes).  

We could workaround it by simply disabling the documents view, but if you click edit under the files view instead of just opening the editor in front of the files it loads the document thumbnails view first.

**Comment by datapharmer** [comment]
@VicDeo Thanks for the changes. I copied the 3 files from pull 428 into my instance, restarted apache and cleared my browser cache, but I am still seeing the 404s unfortunately :-(

**Comment by VicDeo** [comment]
@datapharmer most likely you need to clean `assets` directory in your oc webroot.
This solution is incomplete, it disables previews only if 
`  'enable_previews' => false,` in `config.php`

**Comment by datapharmer** [comment]
I just wanted to provide a quick update that this problem is still present in OC 8.0.2. and documents 0.90

**Comment by VicDeo** [comment]
@datapharmer please post your config.php

**Comment by VicDeo** [comment]
@datapharmer are you still on 8.0.x or migrated to 8.1?

**Comment by VicDeo** [comment]
@datapharmer won't mind testing https://github.com/owncloud/documents/pull/541 ?
It should be easy to apply regardless OC version.

**Comment by VicDeo** [comment]
Fixed with https://github.com/owncloud/documents/pull/541
