### ISSUE TITLE
[documetnation] Explain usage of scripts within https://github.com/owncloud/documents/tree/master/src

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/documents#426]
Should be part of a readme.md or a wiki page

@VicDeo please take care - THX

**Comment by VicDeo** [comment]
@DeepDiver1975  explained in readme.md

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 explained in readme.md

THX

**Comment by DeepDiver1975** [comment]
@LukasReschke FYI

**Comment by LukasReschke** [comment]
Thanks. That makes it much clearer.
