### ISSUE TITLE
http://doc.owncloud.org/server/8.0/developer_manual/core/theming.html

### ISSUE THREAD

**Issue by arm2arm** [owncloud/documents#429]
Unreleated sentance at the end of 
http://doc.owncloud.org/server/8.0/developer_manual/core/theming.html
"But this is unlikely at least in the upcoming updates (5.0.x). ownCloud aims to give further information in this case."
But we are reading already oc8.x docs:)

**Comment by VicDeo** [comment]
@arm2arm thnx. Are you sure it is about documents, not documentation https://github.com/owncloud/documentation/issues/ ?

**Comment by arm2arm** [comment]
oops wrong place sorry:)
