### ISSUE TITLE
What is the stable5 branch for?

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/documents#430]
@VicDeo

**Comment by VicDeo** [comment]
er... for OC5?

**Comment by LukasReschke** [comment]
Do we even bundle documents with oC5?

**Comment by VicDeo** [comment]
@LukasReschke 
No, it's not. According to https://github.com/owncloud/documents/blob/stable5/appinfo/info.xml#L8
this branch can be dropped.

**Comment by LukasReschke** [comment]
Dropped. Thanks for clarification.
