### ISSUE TITLE
Documents app broken on master

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/documents#431]
I just checked out current master of core and this app and get this JS error when trying to create a ODF document or editing it:

```
 Uncaught Error: Tried to register widget with id==mainContainer but that id is already registered
```

**Comment by LukasReschke** [comment]
Could be related to some changes in 5.6 – let me dig into this…

**Comment by LukasReschke** [comment]
Probably https://github.com/piwik/piwik/issues/6465#issuecomment-59874136 – let me add a check to core…

**Comment by MorrisJobke** [comment]
fixed with https://github.com/owncloud/core/pull/13593
