### ISSUE TITLE
Applying patches fails on master

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/documents#433]
```
➜  documents git:(master) ✗ ./src/updateWebODF.sh build/webodf/
cp: build/webodf/webodf/webodf.js: No such file or directory
cp: build/webodf/webodf/webodf-debug.js: No such file or directory
cp: build/webodf/programs/editor/dojo-amalgamation.js: No such file or directory
cp: build/webodf/programs/editor/Tools.js: No such file or directory
cp: build/webodf/programs/editor/Editor.js: No such file or directory
cp: build/webodf/programs/editor/EditorSession.js: No such file or directory
cp: build/webodf/programs/editor/MemberListView.js: No such file or directory
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
cp: build/webodf/programs/editor/editor.css: No such file or directory
patching file js/3rdparty/webodf/editor/EditorSession.js
patching file js/3rdparty/webodf/editor/Editor.js
Hunk #1 succeeded at 531 (offset 148 lines).
patching file js/3rdparty/webodf/editor/MemberListView.js
patching file css/3rdparty/webodf/editor.css
patching file js/3rdparty/webodf/editor/Tools.js
Hunk #5 FAILED at 277.
1 out of 5 hunks FAILED -- saving rejects to file js/3rdparty/webodf/editor/Tools.js.rej
```

The reject file contains: 
```
***************
*** 271,277 ****
                      });
                      closeButton.placeAt(toolbar);
                  }
- 
                  setEditorSession(editorSession);
              });
          };
--- 277,283 ----
                      });
                      closeButton.placeAt(toolbar);
                  }
+                 toolbar.startup();
                  setEditorSession(editorSession);
              });
          };
```

WebODF is on commit 8d8fc02

@VicDeo

**Comment by LukasReschke** [comment]
@VicDeo Please take a look. THX.

**Comment by VicDeo** [comment]
@LukasReschke Upstream sync has no sense until https://github.com/kogmbh/WebODF/issues/551 is fixed

**Comment by LukasReschke** [comment]
It is no upstream sync. This is on 8d8fc02 – I just want to add some additional patches to our version.

**Comment by LukasReschke** [comment]
If there is another way to apply some custom patches let me know ;-)

**Comment by VicDeo** [comment]
@LukasReschke 
From readme.md https://github.com/owncloud/documents/blob/master/README.md
>>
 WebODF upgrade

>Build WebODF:

>git clone https://github.com/kogmbh/WebODF.git webodf
mkdir build
cd build
cmake ../webodf
make webodf.js-target
Refresh code and create a new branch:

>cd /path/to/documents
git checkout master
git pull --rebase
git checkout -b new-branch
Run upgrade script:

>./src/updateWebODF.sh /path/to/WebODF/build/dir
Resolve confilcts in patches (if any). Commit changes.


`./src/updateWebODF.sh build/webodf/` has a little sense unless you have pre-built WebODF files  in `documents/build/webodf`

**Comment by LukasReschke** [comment]
`documents/build/webodf` contains a built of WebODF in version 8d8fc02 which is what we use according to the version header. So when running the `updateWebODF.sh` command I'd expect not to get any conflicts as it is the same version as we use?

Or is it really expected that the .patch files don't apply?

**Comment by VicDeo** [comment]
@LukasReschke ah, wait...  `build/webodf/webodf/webodf.js:`
I guess you need to run  `./src/updateWebODF.sh build/` instead

**Comment by kossebau** [comment]
Take a closer look at https://github.com/owncloud/documents/blob/master/src/updateWebODF.sh#L4 ;)
Whoever wrote the section in the README.md should have tried it better, not complete.

**Comment by kossebau** [comment]
Another advise for less frustrations: Besides also using the target `editor-compiled.js-target` one needs to make also sure it is a fresh build dir, some versions of webodf buildsystem fail to properly detect changes in dependencies, so rebuilding another version over an old might result in garbage.

Hopefully the future is brighter for downstream with https://github.com/kogmbh/WebODF/pull/845 and ready made packages.
But as @VicDeo mentioned, collab editing not bug free currently :cry:

**Comment by LukasReschke** [comment]
Thanks @kossebau. – Much appreciated! I'll try that then.

**Comment by karlitschek** [comment]
@kossebau do you have an estimation when there will be a stable collab edition build available?

**Comment by LukasReschke** [comment]
@VicDeo Can you please correct the README – thx.

**Comment by kossebau** [comment]
@karlitschek when it's done? ;) no estimation sadly, needs someone to go for it.

**Comment by VicDeo** [comment]
@LukasReschke what I need to correct?
the very first step is titled `Build WebODF:` and has step-by-step shell commands needed to build the sources

**Comment by LukasReschke** [comment]
From https://github.com/owncloud/documents/issues/433#issuecomment-71194251:

> Take a closer look at https://github.com/owncloud/documents/blob/master/src/updateWebODF.sh#L4 ;)
Whoever wrote the section in the README.md should have tried it better, not complete.

**Comment by kossebau** [comment]
@VicDeo one thing that might have confused you because of names: WebODF is actually a meta-project, where both the library webodf.js resides, but also some other products based on it.
So when you build something from the sources in the repo, there is not one target, but multiple to select from. It is more obvious in recent versions, where the targets are properly prefixed with "product-".

**Comment by kossebau** [comment]
(and the (collab)editor is considered another product)

**Comment by VicDeo** [comment]
@LukasReschke is this OK? https://github.com/owncloud/documents/pull/435

**Comment by LukasReschke** [comment]
That works like a charm. Thank you. – I'll close this one then.

Thanks @kossebau for your support here. That is really awesome!
