### ISSUE TITLE
Documents refuses to Enable After Upgrade to OC8

### ISSUE THREAD

**Issue by 19kestier** [owncloud/documents#448]
The Documents app was automatically disabled after I upgraded my server on Digital Ocean running Ubuntu 14.04 Server to ownCloud 8. Then when I clicked Enable, it says "App directory already exists".
![screenshot 2015-02-09 at 8 22 44 pm](https://cloud.githubusercontent.com/assets/4749568/6119643/aaaf36c6-b099-11e4-8e98-b3171d9a9269.png)

**Comment by karlitschek** [comment]
Are you sure you followed the upgrade instructions? Please replace the complete owncloud goler with the new version and only keep the config and data directories.

**Comment by 19kestier** [comment]
No I didn't. I just ran a quick 'sudo apt-get dist-upgrade'. Any idea on how I can fix what I did?

**Comment by RealRancor** [comment]
@19kestier
Just remove the /apps/documents folder and try again

**Comment by 19kestier** [comment]
My admin page is broken too though, so it looks like I'll need to reinstall ownCloud :(

**Comment by VicDeo** [comment]
@19kestier it looks like you need to try removing 3rdparty apps one by one. 
Some of them are probably not compatible with OC8

**Comment by VicDeo** [comment]
@19kestier move everything outside the apps folder leaving only the following list: https://github.com/owncloud/core/tree/stable8/apps
and put them back one by one checking the admin page on each iteration

**Comment by VicDeo** [comment]
Might be a duplicate of https://github.com/owncloud/core/issues/14336

**Comment by VicDeo** [comment]
or https://github.com/owncloud/core/issues/14226

**Comment by VicDeo** [comment]
@19kestier Please remove `/path/to/oc/apps/documents` and retry
Should work

**Comment by 19kestier** [comment]
I removed all folders in the ./owncloud directory except ./config and ./data, then I updated the ownCloud debian package. Everything works great now!
