### ISSUE TITLE
 previews are not working on the documents page, but in the file navigation

### ISSUE THREAD

**Issue by ka0tik0** [owncloud/documents#451]

**Comment by Urknaller** [comment]
apps/documents/index.php:

Change
$previewsEnabled = \OC::$server->getConfig()->getSystemValue('enable_previews', false);
to
$previewsEnabled = \OCP\Config::getSystemValue('enable_previews', 'false');

**Comment by ka0tik0** [comment]
Working nice. Thanks!!
