### ISSUE TITLE
OC8: .doc files not supported?

### ISSUE THREAD

**Issue by zebtom** [owncloud/documents#452]
In OC 7.0.x, .doc files (MS office) could be opened in the Documents app. In OC 8.0, doc files do not open in the Documents app.

Is .doc format no longer supported in the documents app?

**Comment by karlitschek** [comment]
@VicDeo What do you think? Should work, right?

**Comment by Sugaroverdose** [comment]
In my environment(OC8+libreoffice) i can preview and edit .doc files.

**Comment by RealRancor** [comment]
@zebtom 
Have a look at:

http://doc.owncloud.org/server/8.0/admin_manual/configuration/collaborative_documents_configuration.html#enabling-and-testing-ms-word-support

for some pointers / debugging steps.

**Comment by zebtom** [comment]
Oops, my mistake. MS Word support was not enabled in my OC8 install.

Works fine now
