### ISSUE TITLE
Feature request: Filetype icons on preview thumbnails

### ISSUE THREAD

**Issue by edgeHB** [owncloud/documents#454]
Hey there,

just one feature request (hope i'm in the right place):

On preview thumbnails of documents (doc, docx, odt, pdf and so on) should be a small filetype icon in one corner. Those documents often have a white background, which looks not very nice as a small thumbnail on the default white background of the file app. It is nearly impossible to see, that there actually is an icon (for someone who doesn't know, it seems, that there is an icon missing).

See attached screenshot :)

![feature_request](https://cloud.githubusercontent.com/assets/7556305/6252405/612a7774-b79a-11e4-8de5-220741b8d588.png)

**Comment by VicDeo** [comment]
@edgeHB Please reopen in core since all previews are done there https://github.com/owncloud/core/tree/master/lib/private/preview
