### ISSUE TITLE
[Feature Request] Have Documents use the asset-pipeline

### ISSUE THREAD

**Issue by andriesinfoserv** [owncloud/documents#455]
Documents doesn't appear to be able to use the asset-pipeline introduced recently.  It would be nice if it did. 
thanks

**Comment by VicDeo** [comment]
@andriesinfoserv IIRC it already fixed in core https://github.com/owncloud/core/commit/e0d1fa554f85bd73ba69aff54d895e38c776175e
and released with OC7.0.3

**Comment by andriesinfoserv** [comment]
you're right. it appears i was actually having an issue with yslow, as just now after refreshing yslow, it reports the js files were properly combined. sorry for the noise and thanks for your time.
