### ISSUE TITLE
No txt editor in "mobile mode"

### ISSUE THREAD

**Issue by oparoz** [owncloud/documents#465]
Owncloud 8.0.2
Documents 0.9.0

### Steps
1. Make your browser window narrow until the sidebar disappears
2. Click on a txt file

### Expected
I should see an editor and should be able to edit text

### Actual
Everything below the navigation bar is blank
If you widen the browser, the editor shows up at some point.

**Comment by VicDeo** [comment]
>Click on a txt file

Please reopen here https://github.com/owncloud/files_texteditor
