### ISSUE TITLE
Expire document shared by link after download

### ISSUE THREAD

**Issue by svoop** [owncloud/documents#466]
This is a feature suggestion when sharing a document as link:

![screen shot 2015-03-24 at 20 20 29](https://cloud.githubusercontent.com/assets/7255/6810830/d7dc0822-d263-11e4-909a-ed450494daaa.png)

How about one more checkbox:

* [x] Expire immediately after download

When used together with a date triggered expiration, the link would not work any longer than absolutely necessary.

What do you think?

**Comment by VicDeo** [comment]
@svoop  sharing-related enhancements should be opened in core.
This app is not about sharing, it just uses API/UI provided by core

**Comment by svoop** [comment]
@VicDeo Thanks for the hint, I've opened one for core.
