### ISSUE TITLE
webodf - new version (0.5.6)

### ISSUE THREAD

**Issue by aqxavier** [owncloud/documents#469]
We have a new webodf version (0.5.6) stable ..
I tried to compile this new version, but not succeeded.
There is a mismatch in the version currently used (0.4.2)?
This new version of webodf has new features ... This provided the update to the latest version of webodf?

**Comment by VicDeo** [comment]
@aqxavier see https://github.com/owncloud/documents/pull/354#issuecomment-54651167

**Comment by VicDeo** [comment]
in short: until these issues are fixed upstream sync is not safe. That's why https://github.com/owncloud/documents/pull/419 is not megred
Syncing with upstream needs UI adaptation.

**Comment by VicDeo** [comment]
Synced with 0.5.7 in https://github.com/owncloud/documents/issues/492
to be released with 8.1
