### ISSUE TITLE
clickable links in documents

### ISSUE THREAD

**Issue by M4rtinK** [owncloud/documents#470]
It would be very useful to be able to insert clickable links to the document in the document editor. Even just simple
* does it start with *http://* or *https://* ?
* turn it into a clickable link!

would do wonders! :)

**Comment by RealRancor** [comment]
Hi,

when reading this correctly https://github.com/owncloud/documents/issues/122 it seems this should be rather reported/requested at WebODF. Maybe this is also already included in the newer WebODF version (Ref: https://github.com/owncloud/documents/issues/469)

**Comment by VicDeo** [comment]
duplicate of https://github.com/owncloud/documents/issues/122
unsupported by WebODF build we using
