### ISSUE TITLE
broken document: otpoll.php: invalid date

### ISSUE THREAD

**Issue by DoNck** [owncloud/documents#471]
Hi there! I'm running OC on a wheezy, and I encounter an issue during a collaborative edition of a document.

At some point I had the feelink that something was broken as I could'nt see updates from my collaborator. I tried to refresh the document, and since, it is impossible to open.

To keep working on the doc, I had to download it, rename, upload and work on the renamed document, but all the history is lost (I presume) and permissions must be set once again on that new document.

So when I try to open the broken doc, I have the spinner spinning... and that's all. I don't think it is browser related as I have the same issue with chromium. I tried disabling gzip using the .htaccess trick (described here: https://github.com/owncloud/documents). No change.

I checked FireFox's console:
After ` POST http://myserver/owncloud/index.php/apps/documents/ajax/otpoll.php`
I get a:
`RangeError: invalid date" from jQuery`
and then, periodically, a new POST request followed by:
`RangeError: Requested steps (6349) exceeds available steps (6345)`.
(The nuber is incremented at every request.)

I sniffed the first payload that comes back for the POST and wrote a small script to very basically analyse the JSON message it returns:

```
//var response=the JSON object
console.log(response.ops.length + " operations");

var dbkup=0;
for(var k in response.ops){
  var op=response.ops[k];
  var ts=op.timestamp;
  var d= new Date(ts);
  if (d=="Invalid Date"){
    console.log("Invalid Date: "+ts);
  }
  if (dbkup > d){
    console.log('earlier ts found: '+ts);
  }
  if (dbkup == d){
    console.log('same ts found: '+ts);
  }
  dbkup=d;
}
console.log('date checking done!');
```
I attach the output to this ticket. Basically, I never got any consecutive operations with the same timestamp, but timestamps do not seem to be ordered (as ints). Some of them are much longer, may be meaning they are supposed to be in microseconds:

```
{"optype":"InsertText","memberid":"38","timestamp":1428353211667,"position":6642,"text":" ","moveCursor":true}
{"optype":"AddMember","memberid":"47","timestamp":"1428354482","setProperties"
```

In my script, new Date(ts) fails on these long timestamps. I don't know if that could be the cause.
I hope it helps and I'm ready to provide more testing if required, I kept the broken document for that purpose.

**Comment by DoNck** [comment]
I ran a `grep -RiI 'otpoll' /var/www/owncloud apps/documents/`
an found two files containing otpoll.js:
```
apps/documents/appinfo/routes.php:		array('name' => 'session#poll', 'url' => 'ajax/otpoll.php', 'verb' => 'POST'),
apps/documents/js/ServerFactory.js:                args.url = OC.filePath('documents', 'ajax', 'otpoll.php');
```

So I tried to place a breakpoint in FFox on ServerFactory.js and see what happens. Without changing anything else, now I get a different message:

```
POST 
http://myserver/owncloud/index.php/apps/documents/ajax/otpoll.php [HTTP/1.1 200 OK 293ms]
uncaught exception: Inserting local cursor a second time.
```

This time, the message was both displayed from console.log() and alert()

I'm trying to reproduce this, but currently I can't :/

**Comment by DoNck** [comment]
Extra bad news: some edits are lost when the document is downloaded from the files, so downloading and uploading the file loses some data.
Based on the script I posted, I could recover missing text from the otpoll.php returned payload, so at least data are stored somewhere else.

**Comment by VicDeo** [comment]
@DoNck all ops are stored in `oc_documents_op` table. You can locate op with an incorrect time and trim time to be in seconds.

**Comment by DoNck** [comment]
Thanks for you help @VicDeo ! Thanks to you I could try to investigate a little more !

So first, it seems normal that different type of operations use different timestamp precisions. (I checked using the payload of a working document). From my observations:
10 digits precision: AddMember, RemoveMember, 
13 digits precision: AddCursor, MoveCursor, SplitParagraph, InsertText, RemoveText, ApplyDirectStyling

BUT one of my RemoveCursor entries within the problematic payload has only 10 digits (1428450120). So It looks like I should add three zeros to this one instead of trimming other values. Do you agree ?

I also noticed that two operations share that particular timestamp :

```
{
'optype': 'RemoveCursor',
'memberid': '93',
'reason': 'server-idle',
'timestamp': '1428450120'
},
{
'optype': 'RemoveMember',
'memberid': '93',
'timestamp': '1428450120'
},
```

From mysql, I replaced the timestamp 1428450120 by 1428450120000 on that particular RemoveCursor entry:
```
mysql> UPDATE oc_documents_op SET opspec = '{"timestamp": "1428450120000", "reason": "server-idle", "optype": "RemoveCursor", "memberid": "93"}' WHERE seq = '8194';
Query OK, 1 row affected (0.04 sec)
Rows matched: 1  Changed: 1  Warnings: 0
```
Now I see the corrected value coming in the payload, but still I can see `RangeError: invalid date` in the console and it didnt fix the document :(

I also tried with 1428450121000 instead of 1428450120000 to make the timestamp different and it didn't fix the problem either.

BTW, I checked the system time on my server and it seems well set.

Good to know: one of my laptop clients has a poor Wi-Fi adapter and its connection to OC is not very stable, so I have a lot of RemoveMember/AddMember on that problematic document.

**Comment by VicDeo** [comment]
@DoNck can you test https://github.com/owncloud/documents/issues/533 ?

**Comment by DoNck** [comment]
I replaced my op.php file with your new version.

My broken document is still not being displayed, but reading the console I don't get the "RangeError: invalid date" nor the "RangeError: Requested steps (6349) exceeds available steps (6345)." errors anymore.

Note: I don't see the former POST request "http://myserver/owncloud/index.php/apps/documents/ajax/otpoll.php"
And I get plenty of usual preview errors (404)
https://myserver/owncloud/index.php/core/preview.png?file=%2FGeek%2FPython.odt&x=200&y=200&c=93dea2776535e563fc4c7ead9ba9e96a&forceIcon=0
plus two new 404:
https://myserver/owncloud/index.php/apps/documents/ajax/genesis/mykujvuw98eylapcjpb8fkebq2oknu?requesttoken=UhzmNaFsLCfH7NPMfL%2BwLEybHaQdsh (404)
https://myserver/owncloud/index.php/apps/documents/ajax/genesis/mykujvuw98eylapcjpb8fkebq2oknu?requesttoken=UhzmNaFsLCfH7NPMfL%2BwLEybHaQdsh (404)

I'll give a new try to the collaborative editing and tell you if anything goes wrong. At least, non-collaborative edition seems to stay functional.
