### ISSUE TITLE
Verify the OCS ID

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/documents#479]
The current entry of the ocsid is `166045` in all branches:
https://github.com/owncloud/documents/blob/master/appinfo/info.xml#L12
https://github.com/owncloud/documents/blob/stable8/appinfo/info.xml#L12
https://github.com/owncloud/documents/blob/stable7/appinfo/info.xml#L15

However that app is only for oC 7: https://apps.owncloud.com/content/show.php?content=166045
oC 8.0 (and later**?**) should use `168711`: https://apps.owncloud.com/content/show.php?content=168711

This causes problems, when people try to enable the app from the recommended section rather then the disabled section: https://github.com/owncloud/core/issues/16092

Manually changing the ocsid resolves the issue.

**Comment by VicDeo** [comment]
@nickvergessen thanks!
master https://github.com/owncloud/documents/issues/482
stable8 https://github.com/owncloud/documents/pull/484
