### ISSUE TITLE
Libreoffice/openoffice don't work

### ISSUE THREAD

**Issue by stefkey** [owncloud/documents#489]
Hi,

in my server the path to open office is /usr/lib/openoffice/program
I have set in config/config.php   'preview_libreoffice_path' => '/usr/lib/openoffice/program',
When I set in the admin-panel under Documents "Local" and I click "Apply and test" the it shows "Conversion failed. Check log for details." 
But in the apache server error log is no message and in the owncloud log also. I have set the debug-level to 0! But there is no message.
What can I do?
owncloud 8.0.3

**Comment by stefkey** [comment]
sorry, now I found the following in the own cloud log:
Warning	documents	Conversion test failed. Raw output:sh: /usr/lib/openoffice/program: Permission denied

I search now...

**Comment by stefkey** [comment]
i don't found the solution. My web server is www-data, under there is a group www-data.
So I change the owner of
/tmp
/usr/lib/openoffice/program
/usr/lib/openoffice/program/*
but the same error: Conversion test failed. Raw output:sh: /usr/lib/openoffice/program: Permission denied

And now, how can I found the solution?

My owncloud install is in default config. I dont understand the problem.

**Comment by VicDeo** [comment]
@stefkey I can guess that your webserver user has not enough permissions to execute `/usr/lib/openoffice/program`

**Comment by stefkey** [comment]
Thanks! But when I change the owner ob all files in /usr/lib/openoffice/programm to www-data (chown www-data:www-data *) then the web server can execute, or not?

**Comment by VicDeo** [comment]
@stefkey `runuser -u www-data -c /usr/lib/openoffice/program` should answer this question. 
IMO it's better to set an executable bit for other instead of chowning

**Comment by sndrr** [comment]
I suppose this one can be closed?

**Comment by VicDeo** [comment]
@stefkey I'm closing this issue. Please reopen if it is still reproducible.
