### ISSUE TITLE
Unable to enable the documents app

### ISSUE THREAD

**Issue by jab416171** [owncloud/documents#493]
I just upgraded to version 8.0.4, and when I try to enable the documents app, it says: App does not provide an info.xml file

**Comment by RealRancor** [comment]
Hi,

@jab416171 
thats not an issue within the documents app itself but mostly with your system not shipping the needed intermediate certificate for the connection to the appstore. See the duplicate issues at core:

https://github.com/owncloud/core/issues/14840 (and tons of other duplicates)

for a possible workaround.

**Comment by VicDeo** [comment]
@jab416171 is it possible to enable other apps?
As a workaround you can extract stable8 https://github.com/owncloud/documents/archive/stable8.zip into the `apps` directory

**Comment by jab416171** [comment]
@VicDeo Thanks, downloading the zipped stable8 worked.
