### ISSUE TITLE
Accidental translatable strings from webodf.js on Transifex

### ISSUE THREAD

**Issue by vidaren** [owncloud/documents#496]
Today I find some new untranslated strings from webodf.js on Transifex, e.g. "document-styles", "bold", "italic", "pt". My guess is that they appear because the minified webodf.js has a function called t(a,b) which is seen as a translation function by some string extractor when in fact it is not a translation function. I will leave the strings untranslated for now, hoping they go away when this issue has been resolved.

**Comment by VicDeo** [comment]
@vidaren thanks for the heads up

**Comment by zinks-** [comment]
I came here to report two of these ([document-styles](https://github.com/owncloud/documents/blob/master/js/3rdparty/webodf/webodf.js#L242), document-content), I think I got caught by the other ones :/
This should be spread to the entire transifex team so that nothing breaks!

**Comment by vidaren** [comment]
@zinks-  I think nothing will break, because the translated strings will not be used for anything. @VicDeo am I right?

**Comment by zinks-** [comment]
Just tested master and indeed it doesn't seem to be broken :) (relief:)

**Comment by VicDeo** [comment]
@DeepDiver1975 afaik transifex has no options to exclude a file from translation, hasn't it?

**Comment by DeepDiver1975** [comment]
there is an ignore list which can be used - https://github.com/owncloud/administration/blob/master/jenkins/translation_sync/l10n.pl#L35

**Comment by vidaren** [comment]
So we need a new file, [l10n/ignorelist](https://github.com/owncloud/documents/blob/master/l10n/ignorelist), with the following contents:
```
js/3rdparty/webodf/webodf.js
```
Should be straightforward, who will do this?

**Comment by vidaren** [comment]
OK, I made a pull request: https://github.com/owncloud/documents/pull/515
Please review.

**Comment by DeepDiver1975** [comment]
fixed with #515 - THX @vidaren
