### ISSUE TITLE
Document preview not displaying correctly

### ISSUE THREAD

**Issue by dhsc19** [owncloud/documents#505]
When I click on the filename (not the edit button, but the filename itself) of a document (ODT or DOCX), I'm getting stuff like:

PK�	�E^�2''mimetypeapplication/vnd.oasis.opendocument.textPK�	�E�@}��Thumbnails/thumbnail.png�PNG  IHDR�zA��_IDATx���! �@�+? �q�`b{f\��|

**Comment by nkinkade** [comment]
I'm seeing this as well.  I haven't yet been able to figure out why this is happening.  The Documents app appears to be returning the ODF document as expected, and I slightly suspect this could be a core Files issues.  The returned ODF document is not being displayed in it's own container but rather is being literally rendered in the browser, replacing the entire OC interface.  I'll keep looking, but wanted to flag that this is affecting multiple people.

**Comment by eottone** [comment]
Same here, using 0.9.0 (OC 8.1.0).
Preview of odt/doc* works well (trivial issue with Close button occasionally displayed twice) with previous versions of Documents, however I have the "spinner spin for ages" problem when I try to edit them (recommendations in README.md didn’t shed any light and no significant event is logged).

**Comment by nkinkade** [comment]
I should note that I'm using OC 8.1.0 and Documents 0.10.0.  Also, I'm not seeing any PHP errors, nor Javascript errors in the browser console, nor any errors fetching files across the network.  If I revert to Documents 0.9.0, previews of ODF files work fine, but I get the endless spinner when I try to edit a document in the Documents app (#502).  So I take back my earlier comment that this is likely a Files issue because simply reverting to an older version of Documents fixes this.

**Comment by tony5** [comment]
I am also having this same issue on a fresh install of 8.1 on apache 2.2 and php 5.4

**Comment by niandubay** [comment]
same issue here... oc8.1 and documentos 0.10 :-1:

**Comment by godemptiness** [comment]
same issue

**Comment by fifh** [comment]
same issue, oc8.1, documents 0.10, centos 7, php 5.4, apache 2.4...

**Comment by nucshuco** [comment]
Same Here
![capture](https://cloud.githubusercontent.com/assets/8262089/8845129/e646c908-30d0-11e5-8a99-d3a88a7c1f80.PNG)

**Comment by jirutka** [comment]
Same problem here.

documents 0.10.0, OC 8.1.0, PHP-FPM 5.5.26, nginx 1.7.6, Gentoo Linux

**Comment by RealRancor** [comment]
Just also here as a ref: https://github.com/owncloud/documents/issues/507#issuecomment-120627478

Main app developer is on vacation so please have some patience. In general adding a "same here" won't speed up fixing a issue.

**Comment by mokkin** [comment]
In my case I can open ODT file from inside the documents app but not inside the files app.
![bildschirmfoto_2015-07-30_18-25-56](https://cloud.githubusercontent.com/assets/2938748/8988872/0a26af3c-36e9-11e5-969d-9d674c822d6c.png)
![bildschirmfoto_2015-07-30_18-30-38](https://cloud.githubusercontent.com/assets/2938748/8988883/1b38fcee-36e9-11e5-894e-5f283eda8e8e.png)

**Comment by dominix** [comment]
I have the very same issue. (OC 8.1.1.beta1)

**Comment by lfratini** [comment]
Same here 
Environment : Oc 8.1, Centos 7 , php 5.4.16 , nginx 1.9.3-1  Libreoffice 4.2.6.3-5, Documents 0.10 

![owncloud8errror](https://cloud.githubusercontent.com/assets/10744873/9040489/da9ab7fa-3a02-11e5-93fd-0c2ebba85e01.PNG)

**Comment by Pawel-Panek** [comment]
The bug is in js/viewer/viewer.js https://github.com/owncloud/documents/blob/master/js/viewer/viewer.js#L70. The var name 'location' works like window.location and browser gets redirect when value to 'location' is assigned. Replacing var name 'location' with something else, eg 'fileloc' will make the viewer working. Also add 'var fileloc;' to https://github.com/owncloud/documents/blob/master/js/viewer/viewer.js#L61

**Comment by VicDeo** [comment]
@Pawel-Panek thanks! 
Can you confirm that https://github.com/owncloud/documents/pull/522 fixes it?

**Comment by Pawel-Panek** [comment]
Thaks! Works good now.

**Comment by VicDeo** [comment]
@lfratini @dominix @mokkin more volunteers to test https://github.com/owncloud/documents/pull/522 ?

**Comment by idef1x** [comment]
@VicDeo : works for me too now :)
Thanks!

**Comment by vgiralt** [comment]
#522 tested. Preview works.

**Comment by jirutka** [comment]
It works. However, it seems that there’s some graphic glitch…

![screen](https://cloud.githubusercontent.com/assets/949228/9060322/d5999860-3ab2-11e5-994c-88c5b190dad6.png)

Can anyone else confirm this?

**Comment by alleyoopster** [comment]
thanks for the fix, all working for me now

**Comment by lfratini** [comment]
Thanks Guys, It Works !!!
I 've attached the image 
![selection_001](https://cloud.githubusercontent.com/assets/10744873/9107693/a5a667e6-3c29-11e5-86cd-7afcc38102a0.png)
