### ISSUE TITLE
App not shown in app menu

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/documents#508]
After updating my production system to 8.1 (via debian repository), I wasn't able to open the documents app anymore, only a loading spinner was shown forever. I checked the version and was surprised that it was still 0.9.0. Therefore I 'updated' the app by disabling it via the command line, deleting the app folder and finally (re)installing the app via the internal app management of the web UI.

Now, the app _is_ installed according to the web UI:
![bildschirmfoto von 2015-07-09 21-49-59](https://cloud.githubusercontent.com/assets/1374172/8605279/7bd871d0-2684-11e5-9172-e5d570cbe681.png)
However, I cannot select it in the app menu, nor is it listed with ``occ app:list``:
```
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.1
 - contacts: 0.4.0.0
 - external: 1.2
 - files: 1.1.9
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - gallery: 0.6.0
 - mail: 0.1.3
 - news: 5.3.8
 - notes: 1.0.0
 - provisioning_api: 0.2
 - tasks: 0.6.0
 - templateeditor: 0.1
Disabled:
 - encryption
 - files_locking
 - files_videoviewer
 - firstrunwizard
 - search_lucene
 - user_external
 - user_ldap
 - user_webdavauth
```

Is there any way to cleanly uninstall this app?

**Comment by RealRancor** [comment]
Have noticed the same. The /documents folder on the filesystem is empty so i'm not sure if this is an issue within the appstore, the documents app or core itself. Downloadling the app directly from:

https://apps.owncloud.com/content/show.php/Documents?content=168711

works without a problem.

**Comment by t2d** [comment]
I'm experiencing the exact same problem.

**Comment by karlitschek** [comment]
@VicDeo Can you have a look?

**Comment by nazar-pc** [comment]
Same here, fresh ownCloud installation, apps/documents is empty, while enabled in UI.

**Comment by simonpoole** [comment]
This (app directoy empty, app marked as activ, but naturally isn't) happens with the upgrade to 0.10.0 from a previously working 0.9.0 version via the app admin interface too.

**Comment by niandubay** [comment]
same problem here. documents app is not listed. documents folder empty...

**Comment by Schmaetz** [comment]
Same Problems with Documents. After installing the App and reloading the appmanager, documents are deactiv. Manuell Download of documents don't solve the problem.

**Comment by RealRancor** [comment]
Make sure you're enabling the downloaded app from the "not active" category.

**Comment by giancarlobi** [comment]
I can enable app after manually download it but when I open an odt to edit continuously loop loader gear and when I stop or backward popup error "Assertion Failed...". No entry into log file or apache log.
Thanks

**Comment by simonpoole** [comment]
@RealRancor it doesn't actually show in the "not active" category.

**Comment by RealRancor** [comment]
@giancarlobi Please create a new issue using the issue template from https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

@simonpoole Mhh, strange. That actually worked for me.

**Comment by PartisanEntity** [comment]
Same problem as original post.

**Comment by ignoreigor** [comment]
Here my observations again, as I posted in #17602, because I didn't notice the closed flag over there:
I twiddled with owncloud, libreoffice and the documents app, but I got no success. I followed every advice told here and on other posts before. Well, I had problems running libreoffice under the apache's user, but although I removed this problem, the documents app won't work, it even wouldn't try to start libreoffice.

Your hint lets me have a closer look on owncloud's database tables. When I truncated the table "oc_documents_session", owncloud opened the document editor, just like you described with never-opened-before documents.

I still have the issue, that viewing a document doesn't work. Clicking on a document, I got it's raw code, though editing this documents works now. I suppose the .htaccess-entry is ignored or doesn't matches for my installation.

**Comment by RealRancor** [comment]
@ignoreigor Please create a new issue about your "raw code" problem using the issue template from here: https://github.com/owncloud/documents/blob/master/CONTRIBUTING.md#short-version

This issue currently discussed in here is that the documents app doesn't get enabled at all because the /apps/documents/ folder is empty after enabling it.

**Comment by fifh** [comment]
I think this new issue (about the raw code) already exists here : 
https://github.com/owncloud/documents/issues/505
@ignoreigor Join the participants ;-)

**Comment by ignoreigor** [comment]
@fifh: You're right - how could I just ignore #505? Seems it is not solved yet.
@RealRancor: Yeah, this issue is getting more and more offtopic.

**Comment by simonpoole** [comment]
It would be nice if there was some clarity if the issue will be fixed any time soon/a workaround provided or if we should revert to google docs for collaborative editing. 

To quote OC on "official" apps: "They offer functionality central to ownCloud and are ready for production use"

**Comment by nazar-pc** [comment]
@simonpoole, just download archive and extract to `apps` directory

**Comment by RealRancor** [comment]
@simonpoole A workaround is provided since two weeks: https://github.com/owncloud/documents/issues/508#issuecomment-120249639

And please have some patience or revert to google docs if you don't have any.

**Comment by simonpoole** [comment]
@RealRancor the app page still refers to version 0.9.0 how is anybody supposed to know that there 0.10.0 is hiding there?

**Comment by Schmaetz** [comment]
See #502 
Third last post.

**Comment by RealRancor** [comment]
@simonpoole Then please ask instead of throwing such posts like the one in here.

**Comment by simonpoole** [comment]
That the main dev. for the app is on vacation, would have been a sufficient answer. Note that while it is possible to create new documents with the version of the app from the app store, it shows the eternally spinning spinner on existing documents as noted elsewhere.

**Comment by RealRancor** [comment]
Ref: https://github.com/owncloud/documents/issues/507#issuecomment-120627478

**Comment by b7g5r** [comment]
https://github.com/owncloud/documents/issues/520#issuecomment-128542550

**Comment by RealRancor** [comment]
Also a ref for a discussion in core: https://github.com/owncloud/core/issues/18116 If the download links are fixed this should work again.

**Comment by RealRancor** [comment]
Anyone still having this issue please try to update now as it seems to be fixed now.

**Comment by ChristophWurst** [comment]
> Anyone still having this issue please try to update now as it seems to be fixed now.

Yes, it's fixed! Thank you very much :-)
