### ISSUE TITLE
/var/www/owncloud/apps/documents is empty

### ISSUE THREAD

**Issue by b7g5r** [owncloud/documents#520]
### Steps to reproduce
1. activate the "documents" app  in the apps settings
2. look (e. g. via SSH) on the server in the apps folder
3. click in Owncloud on the small arrow in the upper left corner to see the apps overview

I even tried to install the documents app manually by downloading the archive and extracting it to the documents folder, but instead I got an blue „screen“ saying it is going to update, so it did not help…  

### Expected behaviour
There should be files in the /var/www/owncloud/apps/documents folder and an icon "documents" in the apps overview.

### Actual behaviour
/var/www/owncloud/apps/documents is empty and there is no icon "documents" in the apps overview although I have activated documents.

### Server configuration
**Operating system:**
Debian 8 Jessie

**Web server:**
Apache 2.4.10

**Database:**
MariaDB 10.0.20

**PHP version:**
PHP 5.6.9

**ownCloud version:** (see ownCloud admin page)
Owncloud 8.1.0 (stable)

**Updated from an older ownCloud or fresh install:**
fresh install, no update

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - files: 1.1.9
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - mail: 0.1.3
 - provisioning_api: 0.2
 - tasks: 0.7.1
 - templateeditor: 0.1

Disabled:
 - encryption
 - external
 - user_external
 - user_ldap
 - user_webdavauth

(documents is missing although enabled in the apps settings)

**The content of config/config.php:**
[...]
```php
'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://pi1/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_ben',
  'dbpassword' => '7nhiu2rm9lwylqa72mso6onhb80hah',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 1,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'enable_previews' => 'false',
  'mail_smtpmode' => 'php',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'benediktg',
  'mail_domain' => 'openaliasbox.org',
  'mail_smtpauth' => 1,
  'theme' => '',
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
I have enabled (rather for testing) the integration of an external Owncloud and a Dropbox instance.

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
I think no

### Client configuration
**Browser:**
Firefox 39.0

**Operating system:**
Kubuntu 15.04

#### Web server error log
There seem to be no relevant log file lines here.

#### ownCloud log (data/owncloud.log)
(because I even tried to manually download the documents.tar.gz from Github and extract it to the apps/documents folder I got several of these lines:
```
{"reqId":"1ebShzFCD0G8Y3K\/AqK6","remoteAddr":"62.224.127.187","app":"core","message":"No update found at the ownCloud appstore for app 166055","level":1,"time":"2015-08-03T10:12:04+00:00"}
```

#### Browser log
If it helps I can deliver browser logs subsequently.

Here you can see that it is activated but mussing in the apps overview:
![owncloud](https://cloud.githubusercontent.com/assets/9093374/9036540/bfe44e1e-39e2-11e5-8daa-9f9031764f63.png)
and the documents folder is empty:
![owncloud1](https://cloud.githubusercontent.com/assets/9093374/9036580/0b9be5ec-39e3-11e5-9463-eeb9d0b30cc9.png)

**Comment by b7g5r** [comment]
oh, this might be a duplicate of this: https://github.com/owncloud/documents/issues/508

**Comment by beanaroo** [comment]
Just to confirm the exact same behaviour on Arch Linux running Owncloud 8.1

**Comment by b7g5r** [comment]
After I ran
```
git clone --branch stable8.1 https://github.com/owncloud/documents.git
```
in the ```/var/www/owncloud/apps``` folder and ensured that the permissions are set correctly using the bash script from the admin documentation located at https://doc.owncloud.org/server/8.1/admin_manual/installation/installation_wizard.html#setting-strong-directory-permissions it now seems to work properly.

**Comment by b7g5r** [comment]
problem solved
