### ISSUE TITLE
FF38: Content Security Policy error on opening Documents

### ISSUE THREAD

**Issue by mephinet** [owncloud/documents#526]
I upgraded to ownCloud 8.1.0 (stable), and had troubles getting Documents to start again probably #490 or #507. I fixed this by overwriting the deployed version of Documents with github's stable8.1 branch (revision 0eca405b...) version - reporting itself as Documents 0.10.1.

Now, when opening Documents, I see this error in the console:
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://my-hostname-here 'unsafe-eval'").

This error message does not show in Chromium 44.

**Comment by VicDeo** [comment]
@mephinet what exact resource (URL) is being blocked and in which browser?

**Comment by mephinet** [comment]
@VicDeo: thanks for pointing me in the right direction - this is not limited to document, but is a general issue with Firefox 38 and newer - it's already covered by https://github.com/owncloud/core/issues/17758 - therefore I close this issue...
