### ISSUE TITLE
Add a bullet list/ordered list toolbar button

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/documents#529]
This seems quite an oversight - bullet and numbered lists are used a lot and they are supported, but there's no easy way to get them in a document!

**Comment by VicDeo** [comment]
@jospoortvliet  No,they are no supported. Lists creation is not implemented.
See demo  http://www.webodf.org/demo/ci/wodotexteditor-0.5.8/localeditor.html 
and https://github.com/kogmbh/WebODF/issues/32

**Comment by RealRancor** [comment]
Dup of https://github.com/owncloud/documents/issues/377 ?

**Comment by jospoortvliet** [comment]
@RealRancor yeah...
