### ISSUE TITLE
Could not find resource file ...editor.css when trying to open a shared link

### ISSUE THREAD

**Issue by nomeata** [owncloud/documents#530]
This is documents 0.10.1 on owncloud 8.1.1, installed on Debian stable via the official Debian package.

I can edit a ODF document from the normal Files view, and it works fine. If I then, from within the editor, create a share link (of the form `https://owncloud.XXX.de/public.php?service=documents&t=hYXXXX`) and open that, nothing is displayed, and the server log prints
```
{"reqId":"0q\/7KAS3LKZ\/Kr3iwLtI","remoteAddr":"XXX","app":"documents","message":"Could not find resource file \"\/apps\/documents\/css\/3rdparty\/webodf\/editor.css\"","level":3,"time":"2015-08-24T19:27:53+00:00"}
{"reqId":"0q\/7KAS3LKZ\/Kr3iwLtI","remoteAddr":"XXX","app":"remote","message":"The source file \"\/var\/www\/owncloud\/apps\/documents\/css\/3rdparty\/webodf\/editor.css\" does not exist.","level":4,"time":"2015-08-24T19:27:53+00:00"}
{"reqId":"0q\/7KAS3LKZ\/Kr3iwLtI","remoteAddr":"XXX","app":"documents","message":"Could not find resource file \"\/apps\/documents\/css\/3rdparty\/webodf\/editor.css\"","level":3,"time":"2015-08-24T19:27:53+00:00"}
{"reqId":"0q\/7KAS3LKZ\/Kr3iwLtI","remoteAddr":"XXX","app":"PHP","message":"RuntimeException: The source file \"\/var\/www\/owncloud\/apps\/documents\/css\/3rdparty\/webodf\/editor.css\" does not exist. at \/var\/www\/owncloud\/3rdparty\/kriswallsmith\/assetic\/src\/Assetic\/Asset\/FileAsset.php#62","level":3,"time":"2015-08-24T19:27:54+00:00"}
```

I tried to debug this issue a bit, but to my surprise, an `fgrep -r` in the owncloud folder does not find any reference to a `editor.css`, so I really do not know why this `assetic` library wants to access it.

**Comment by nomeata** [comment]
Ah, I found the reference: 
```
			\OCP\Util::addStyle( 'documents', '3rdparty/webodf/dojo-app');
			\OCP\Util::addStyle( 'documents', '3rdparty/webodf/editor' );
			\OCP\Util::addScript('documents', 'documents');
```
https://github.com/owncloud/documents/blob/master/public.php#L39

So where should the `editor.css` come from?

Anyways, if I delete this line everything seems to be working fine.

**Comment by VicDeo** [comment]
@nomeata Thanks for reporting. This is a leftover from a previous WebODF version. It is not needed anymore.
