### ISSUE TITLE
0.10.1 with updated .htaccess - spinner on document load

### ISSUE THREAD

**Issue by pljones** [owncloud/documents#542]
### Steps to reproduce
1. Install package
1. Correct the permissions and ownership to allow app update
1. Update document app to 0.10.1
1. Try to open the Example.odt document using the document app

### Expected behaviour
The document should open.

### Actual behaviour
The app loads the top bar of the editor but the document pane contains only a spinner.

### Server configuration
**Operating system**:
Ubuntu 15.04

**Web server:**
Server version: Apache/2.4.10 (Ubuntu)
Server built:   Jul 24 2015 17:25:18

**Database:**
mysql  Ver 14.14 Distrib 5.6.25, for debian-linux-gnu (x86_64) using  EditLine wrapper

**PHP version:**
PHP 5.6.4-4ubuntu6.2 (cli) (built: Jul  2 2015 15:29:28)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
Package: owncloud
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 60
Maintainer: JÃ¼rgen Weigert <jw@owncloud.com>
Architecture: all
Version: 8.1.1-1

**Updated from an older ownCloud or fresh install:**
Fresh install

**List of activated apps:**
```
Enabled:
 - activity: 2.1.2
 - documents: 0.10.1
 - files: 1.1.11
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - firstrunwizard: 1.1
 - gallery: 14.0.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - user_external: 0.4
Disabled:
 - encryption
 - external
 - files_external
 - files_videoviewer
 - user_ldap
 - user_webdavauth
```
**The content of config/config.php:**
```php
<?php
$CONFIG = array (
  'instanceid' => 'oc1qb21x16zy',
  'passwordsalt' => 'salt',
  'hashingCost' => 10,
  'trusted_domains' =>
  array (
    0 => 'owncloud.drealm.info',
    1 => 'peter.drealm.info',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'version' => '8.2.0.4',
  'dbtype' => 'mysql',
  'dbhost' => 'localhost',
  'dbname' => 'owncloud_db',
  'dbuser' => 'oc_owncloud_admi',
  'dbpassword' => 'dbpassword',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'default_language' => 'en',
  'defaultapp' => 'files',
  'remember_login_cookie_lifetime' => 1296000,
  'session_keepalive' => true,
  'overwrite.cli.url' => 'http://peter.drealm.info/owncloud',
  'has_internet_connection' => true,
  'log_type' => 'owncloud',
  'loglevel' => 0,
  'logtimezone' => 'Europe/London',
  'appstoreenabled' => true,
  'appstore.experimental.enabled' => true,
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'enable_previews' => false,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'preview_office_cl_parameters' => ' --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ',
  'theme' => '',
  'maintenance' => false,
  'secret' => 'secret',
  'mail_smtpmode' => 'php',
  'debug' => true,
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
?

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
All.

**Operating system:**
All.

#### Web server error log
No errors during session.

#### ownCloud log (data/owncloud.log)
Log is empty.

#### Browser log
Console:
```
22:34:25.303 Use of getAttributeNode() is deprecated. Use getAttribute() instead. jquery.min.js:156:0
22:34:26.443 GET 
XHR 
http://peter.drealm.info/owncloud/index.php/apps/documents/ajax/genesis/iklrhjvj7mt5qvykftxg86nk7mcnoz [HTTP/1.1 404 Not Found 49ms]
22:34:26.688 no element found iklrhjvj7mt5qvykftxg86nk7mcnoz:1:1
22:34:27.519 Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src http://peter.drealm.info 'unsafe-eval'"). documents
```

**Comment by VicDeo** [comment]
@pljones I think you need to look through https://github.com/owncloud/core/issues/17758

**Comment by pljones** [comment]
Hi @VicDeo,
That may explain the CSP error.  However, there's no report in https://github.com/owncloud/core/issues/17758 of spinner on load in Document load - it's not clear whether or not it's related.

Thanks,

-- Peter

**Comment by VicDeo** [comment]
@pljones so this is not another face of https://github.com/owncloud/documents/issues/526, isn't it?

**Comment by pljones** [comment]
Aha, that'll be the one -- tricky finding the right words when doing the initial hunt for duplicates.  I'll close this one.
