### ISSUE TITLE
[master] Sharing dialog is broken after right bar is merged

### ISSUE THREAD

**Issue by VicDeo** [owncloud/documents#550]
Good old hack does not work any more. We need a new one.

**Comment by PVince81** [comment]
Just import share.js, share.css from this branch https://github.com/owncloud/calendar/pull/940

**Comment by PVince81** [comment]
Let me know if you need further help

**Comment by VicDeo** [comment]
@PVince81 Thanks, due to your efforts, everything is pretty clear there. :icecream:
