### ISSUE TITLE
Increase version for 9.0

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/documents#556]
Just a warning, when stable8.2 is branched off in core (most likely today), the info.xml needs to be adjusted to allow installing against 9.0:
```xml
	<requiremin>8.0</requiremin>
	<requiremax>8.5</requiremax>
```
Also the two sections should be changed in favor of the "new" dependencies section:
```xml
	<dependencies>
		<owncloud min-version="8.1" max-version="8.2" />
	</dependencies>
```

At the end the app version should also be increased (first or second digit, to allow updates in stable8.2 later, in case it is needed).
Also the version file can be melted into the info.xml, e.g.:
```xml
<version>0.11.0</version>
```

**Comment by nickvergessen** [comment]
@VicDeo

**Comment by VicDeo** [comment]
Done
