### ISSUE TITLE
Editing doc/docx

### ISSUE THREAD

**Issue by briskspirit** [owncloud/documents#559]
Hi.

I have upgraded to OC 8.2 from 8.1.3
Documents version was 0.10.2
Apache 2.4.10 , php 5.6.13, Debian 8.2 (all packages is up to date!) 
Went to Admin settings and switched to local OO/LO... Got Saving... forever. With this case ODT editing/creating works fine, but doc/docx - not. Googled...a lot... created temp dir for OO/LO , played with a lot of fixes... no luck. Then got info to install actual version of Docs from here. Downloaded, extracted, installed - got version 0.10.1
Went to Admin settings, choose local - Saved!(green). I thought that all is fine now, gone to see if it so... nope.. doc/docx still don't open(spinning wheel) and now ODT is broken too with ASSERTION error! Tried to switch off gzip - no luck.

Log file:
Call to undefined function OCA\Documents\get_temp_dir() at /var/www/owncloud/apps/documents/lib/converter.php#94

Help please,
Thanks!

**Comment by VicDeo** [comment]
@briskspirit please apply this change to your 0.10.1 https://github.com/owncloud/documents/pull/560/files

**Comment by briskspirit** [comment]
This commit was there... Very strange..

                $params = ' --headless --convert-to ' . escapeshellarg($targetFilter) . ' --outdir '
                        . escapeshellarg($outdir)
                        . ' --writer '. escapeshellarg($infile)
                        . ' -env:UserInstallation=file://'
                        . escapeshellarg(\OC::$server->getTempManager()->getTempBaseDir() . '/owncloud-' . \OC_Util::getInstanceId().'/') . ' 2>&1'
                ;

**Comment by briskspirit** [comment]
Made, now it is trying to open and I got this(on odt/doc/docx):

ASSERTION FAILED:
tried to unsubscribe unknown callback from event "input/compositionstart"

(First time saw this error after update from shipped 0.10.2 to github's 0.10.1)

**Comment by briskspirit** [comment]
Solved. Just truncated all documents tables.

But found another bug - When clicking on Edit when in Files app - it "tries" to go into Docs and then return back to Files.

**Comment by briskspirit** [comment]
@VicDeo , why you closed issue?

bug - When clicking on Edit when in Files app - it "tries" to go into Docs(i think so, but it seems like just a refresh) and then return back to Files.

So pressing Edit link will cause in page refresh. No errors in log, no errors in browser console.

**Comment by VicDeo** [comment]
@briskspirit it was closed automatically due to reference in commit.
Please report wrong Edit behavior separately, it's unrelated to `Editing doc/docx`
