### ISSUE TITLE
wrong Edit behavior in OC 8.2

### ISSUE THREAD

**Issue by briskspirit** [owncloud/documents#564]
Upgrade from 8.1.3 to 8.2 (On 8.1.3 all was fine)
Documents version 0.10.1(from GitHub)
Apache 2.4.10 , php 5.6.13, Debian 8.2 (all packages is up to date!) 

bug - When clicking on Edit when in Files app - it "tries" to go into Docs(i think so, but it seems like just a refresh) and then return back to Files.

So pressing Edit link will cause in page refresh. No errors in log, no errors in browser console.

**Comment by VicDeo** [comment]
@briskspirit thanks :)
Reproducible with master/8.2

**Comment by briskspirit** [comment]
new bug hunter in your squad ;)

**Comment by pascaldaniela** [comment]
Same behaviour here: 
owncloud 8.2.0, upgraded from 8.1.3 (all fine) 
Documents 0.11.0 from here:  https://github.com/owncloud/documents/archive/v8.2.0.zip
apache 2.4.10, php 5.6.13, Debian 8.2
Editing from Documents app works, editing from Files app same behaviour as briskspirit: goes back to the Home folder

**Comment by fuco809** [comment]
i had the same problem with editing docx and found following working combination:
owncloud 8.2.0 with this documents app version: https://github.com/owncloud/documents/archive/v8.1.4RC1.zip, then change in apps/documents/libs/conversion.php and apps/documents/libs/config.php the function get_temp_dir() to new described here: https://github.com/owncloud/documents/pull/560/files (important: change it in both files) and voila the problems with document apps disappear: edit link working from files and/or from documents. and "apply and test" from admin page in area documents working as well. 

note: i also tried other document app versions, (0.10.2 or v8.2.0), but none of them works for me.

**Comment by pascaldaniela** [comment]
thanks for the hint, fuco809, I just don't feel too much comfortable in using a RC release for my organization's cloud storage. I hope there will be a more stable fix for this.

**Comment by adrianvg** [comment]
I used the Documents app v0.10.2 from an OC-server that worked and wasn't updated with respect to app-versions, as a workaround.

**Comment by xenithorb** [comment]
Still appears to be broken on 8.2.1 
Version 0.11.0

Tried to apply @fuco809's fix but that no longer works (specifically libs/config.php doesn't exist?) 

Grepped code for get_temp_dir and it wasn't found, either.

**Comment by adrianvg** [comment]
Using the backed up 0.10.2 app on the new 8.2.1 OC, made document editing work again. 8-)

**Comment by Yamakasi** [comment]
This also happens on 8.2.2, is this known ?

**Comment by efelon** [comment]
Yes, still happens on 8.2.2 (stable).

**Comment by RealRancor** [comment]
@Yamakasi @efelon The documents app is not shipped with ownCloud so this will also happen in newer versions until a new version of the documents app including a fix is released.

**Comment by hoskyz** [comment]
I have the same problem when I want to edit a document at the beginning again , do not understand why is it, if this works it's not like libreoffice were not installed,

I have seen a response of " fuco809 " with a possible solution, they can detail the steps for an inexperienced person in this?

Thank you

**Comment by RealRancor** [comment]
@hoskyz You need to apply this change https://github.com/owncloud/documents/pull/593/files until a new version of the documents app (not a new version of oC!!!) is released.

**Comment by hoskyz** [comment]
Thank you very much , I understand only change I Have To Green Line the red .

Thank you!

**Comment by RealRancor** [comment]
Chang the red line to the green one :-)

**Comment by pascaldaniela** [comment]
OC 8.2.2 / Documents 0.11.0, changed js/viewer/viewer.js#56 and still the same: "Edit" doesn't work!

**Comment by jancborchardt** [comment]
@VicDeo please check this out. cc @karlitschek

**Comment by VicDeo** [comment]
Checked. Fixed. Merged in 2015
