### ISSUE TITLE
Save and Test stuck saving

### ISSUE THREAD

**Issue by drtomasso** [owncloud/documents#576]
When clicking Save and test, it's stuck "Saving".

Log says:
```
PHP Fatal error:  Call to undefined method OC\\Log::warn() in /var/www/owncloud/apps/documents/lib/converter.php on line 62
```

There might be a type-o in: https://github.com/owncloud/documents/blob/master/lib/converter.php, line 42 and 62

Shouldn't it be `warning()` and not `warn()` ?

**Comment by VicDeo** [comment]
@drtomasso that's Ok.  I think you need to validate your OC and Documents version against this table https://github.com/owncloud/documents/issues/507#issuecomment-150023939

**Comment by VicDeo** [comment]
@drtomasso oops, I take it back. 
Can you please submit a PR with these changes?
