### ISSUE TITLE
Adding Fonts

### ISSUE THREAD

**Issue by RuudschMaHinda** [owncloud/documents#579]
As of now it is impossible to add any fonts to the editor. The company that I work for will need certain fonts available before I am allowed to implement the collaboritive editing.

I can't even figure out on how to add fonts manually. A manual workaround would be nice for now, but consider this a feature request.

**Comment by VicDeo** [comment]
@RuudschMaHinda https://github.com/owncloud/documents/blob/master/README.md#how-to-add-more-fonts

**Comment by RuudschMaHinda** [comment]
That is exactly what I did:

@font-face {
  font-family: "Arial";
  src: url("./fonts/Arial.ttf") format("truetype");
  font-weight: normal;
  font-style: normal;
}
@font-face {
  font-family: "Arial";
  src: url("./fonts/Arial_Bold.ttf") format("truetype");
  font-weight: bold;
  font-style: normal;
}
@font-face {
  font-family: "Arial";
  src: url("./fonts/Arial_Italic.ttf") format("truetype");
  font-weight: normal;
  font-style: italic;
}
@font-face {
  font-family: "Arial";
  src: url("./fonts/Arial_Bold_Italic.ttf") format("truetype");
  font-weight: bold;
  font-style: italic;
}

And it does not show up in the fonts selection. I restarted nginx after adding it as well.

**Comment by RuudschMaHinda** [comment]
If the original document uses Arial, it does show up. But creating a new document, or changing the font in a document that uses a different font, doesn't even give me the option of Arial.

**Comment by RuudschMaHinda** [comment]
It does get stranger still:
my normal company user does not see "Arial" as an option. But my Admin Account does!
Even after relogging the normal user did not have that option.

**Comment by RuudschMaHinda** [comment]
The solution was:
Empty the cache!

Can be closed.
Still, the feature request remains. Being able to easily add fonts would be nice.

**Comment by RealRancor** [comment]
@RuudschMaHinda You can close own issues on your own by hitting the close button below the comment box.
