### ISSUE TITLE
unable to view .ods spreadsheets after upgrade to OC 8.2 / documents 0.11 

### ISSUE THREAD

**Issue by brrrrrrrt** [owncloud/documents#580]
opening .ods spreadsheets does not work anymore after upgrading from owncloud 8.1.4 to 8.2.0

```
Exception: {"Exception":"Exception","Message":"\/files\/xyz.ods is application\/vnd.oasis.opendocument.spreadsheet and is not supported by Documents app","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/documents\/lib\/file.php(62): OCA\\Documents\\File->initViews()\n#1 \/var\/www\/owncloud\/apps\/documents\/controller\/documentcontroller.php(125): OCA\\Documents\\File->__construct(1776227)\n#2 [internal function]: OCA\\Documents\\Controller\\DocumentController->download('\/xyz.ods')\n#3 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#4 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Documents\\Controller\\DocumentController), 'download')\n#5 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Documents\\Controller\\DocumentController), 'download')\n#6 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('DocumentControl...', 'download', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#7 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#8 \/var\/www\/owncloud\/lib\/private\/route\/router.php(282): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#9 \/var\/www\/owncloud\/lib\/base.php(831): OC\\Route\\Router->match('\/apps\/documents...')\n#10 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#11 {main}","File":"\/var\/www\/owncloud\/apps\/documents\/lib\/file.php","Line":193}
```

**Comment by RealRancor** [comment]
@karlitschek From my knowledge the documents app never had spreadsheet support or am i wrong?

**Comment by karlitschek** [comment]
No documents had never spreadsheet support. Maybe this got confused with a browser plugin that shows spreadsheet or something else.

**Comment by brrrrrrrt** [comment]
hmm, i think you are wrong - spreadsheets could not be edited, but if you clicked on a spreadsheet you were able to view it. 

now if you click on a spreadsheet you get an empty white page, see attachment. 

i am sure viewing spreadsheets was working before the owncloud upgrade, did not change my browser, but the owncloud version.
![bildschirmfoto von 2015-11-06 10-46-13](https://cloud.githubusercontent.com/assets/4489013/10994081/368b36b4-8474-11e5-9ad4-a1d910493d4f.png)

and... if spreadsheets are not supported, why does owncloud try to open it?

**Comment by RealRancor** [comment]
@brrrrrrrt Mhhh, could be that i was wrong. Just did a test with:

oC 8.1.4
Documents 0.10.2

- If clicking on a .ods file with an enabled documents app a preview of the spreadsheet is shown.
- If clicking on a .ods file with an disabled documents app the file is just downloaded.

@karlitschek @VicDeo 
Where is this viewer (not edit) capability of the documents app coming from and was it removed in the oC 8.2 version of the documents app?

**Comment by VicDeo** [comment]
@RealRancor https://github.com/owncloud/documents/blob/master/js/viewer/viewer.js#L4
there may be a js error

**Comment by RealRancor** [comment]
@VicDeo So that needs to be reopened or am i wrong?

**Comment by brrrrrrrt** [comment]
@RealRancor, @karlitschek an empty white page when clicking on a .ods file is surely not intended, so  i would say it should be reopened. if you declare viewing of .ods files as not supporteted from now on, clicking on it should at least download the file instead of an empty white page.
