### ISSUE TITLE
Redirect to Filebrowser owncloud 8.2

### ISSUE THREAD

**Issue by team4music** [owncloud/documents#583]
If i click on Edit Files within the Filebrowser i get redirected back to the File Browser. The only way to edit Documents is currently to click on the File or use "Documents" within the Navigation.

Demo: http://screencast-o-matic.com/watch/coXXe1h2mA

Sadly there is no error message.

**Comment by VicDeo** [comment]
duplicate of https://github.com/owncloud/documents/issues/564
