### ISSUE TITLE
Editing Calc/Excel Documents

### ISSUE THREAD

**Issue by frogueat** [owncloud/documents#584]
Documents App is so great. But it would be even greater, if there would be support for Calc/Excel-Documents!!! Please, please, please ... As there is Open-/Libreoffice running on the Server, this app could handle these Filetypes too? Sure - this is probably not an issue - rather more a feature request. I simply did not find any better place to put this. Sorry.

Regards, Günther

**Comment by VicDeo** [comment]
All questions on spreadsheet support go into https://github.com/owncloud/documents/issues/100
in short: no full support in the nearest future.
