### ISSUE TITLE
What about LibreOffice Online ?

### ISSUE THREAD

**Issue by kylejvrsa** [owncloud/documents#597]
Looks like someone has already done some work on this

https://github.com/COMU/libreonline-owncloud

https://www.youtube.com/watch?v=An7D5i34xKM

what do you think?

**Comment by aspdye** [comment]
https://owncloud.org/blog/libreoffice-online-has-arrived-in-owncloud/

Dont know what exactly that means for this App. But since there is an official Reference to this App (or project) i think, that this App will be dropped in the next time.

**Comment by DanScharon** [comment]
as long as LOOL doesn't support multiple users editing the same document in realtime, I don't see any reason to drop this app.

**Comment by VicDeo** [comment]
https://github.com/owncloud/richdocuments
