### ISSUE TITLE
Documents are not opening. Get redirected to root file page. No errors. 

### ISSUE THREAD

**Issue by Stfb** [owncloud/documents#598]
Hi,

I upgraded from owncloud 8.1 to 8.2. Documents app was updated automatically to 0.11.
I can't open any document ODT or DOCX documents, I get the spinning loading animation for 2sec then I get redirected to the root file page.

No errors in the owncloud log or the PHP/Apache log.

I tried with Firefox and Chrome, cleared cache, but none worked.
Any clue?

**Comment by VicDeo** [comment]
@Stfb It looks like you need this fix https://github.com/owncloud/documents/pull/593/files

**Comment by RealRancor** [comment]
@VicDeo Looks also like a duplicate of https://github.com/owncloud/documents/issues/564 ?

**Comment by Stfb** [comment]
Thanks VicDeo! The fix worked. :+1:

**Comment by VicDeo** [comment]
Duplicate of https://github.com/owncloud/documents/issues/564
