### ISSUE TITLE
Avatars as guest issue

### ISSUE THREAD

**Issue by gig13** [owncloud/documents#601]
### Steps to reproduce
1. To obtain exact setup and steps
2.
3.

### Expected behaviour
The document should be viewable as guest and there should not be a 500 response for the avatar image

### Actual behavior
One of the functions involved was set to not work for non-authenticated connections. This resulted in a 500 response code on the ajax request for the avatar image. However the same ajax query worked if you were viewing the document as a guest in a different tab when your first tab was logged in. Part of the fix was to swap @NoAdminRequired for @PublicPage on one function. 

### Server configuration
**Operating system**: RHEL

**Web server:** Apache

**Database:** Percona Cluster

**PHP version:** 5.5.30

**ownCloud version:** 8.1.4

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:**

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** AD

@MorrisJobke

**Comment by MorrisJobke** [comment]
cc @VicDeo

**Comment by gig13** [comment]
More details from @scolebrook :

Exact steps after installing docs app are share the document via public link, the for the internal user to be editing the document and for the guest user (in a different browser) to open the public link. The guest user console will show the 500 errors for the ajax queries to fetch the avatars. If you use the same browser (logged in one tab and open the public link in another) it will work as the public link requests will include the cookies for the authenticated session in the other tab as the server addresses are the same.

To fix this issue I made changes to /core/avatar/avatarcontroller.php after following the logic of the code in the ajax request.

Firstly I changed the security config for the getAvatar function to @PublicPage this fixes the 500 errors and allows the function to run when on the public link. But it also sends the internal users actual avatar which could be a privacy problem and probably why this was set to @NoAdminRequired in the first place. I wanted it to return a generic avatar when on a public link rather than send someone's photo to avoid any privacy concerns.

So here's the entirety of my version of getAvatar. I've included comments to note the start and finish of my alteration to the function.

```
/**
* @PublicPage
*
* @param string $userId
* @param int $size
* @return DataResponse|DataDisplayResponse
*/
public function getAvatar($userId, $size) {
if ($size > 2048) {
$size = 2048;
} elseif ($size <= 0) {
$size = 64;
}

/*** MOD BEGIN ***/
if ($this->userSession->isLoggedIn() && !is_null($this->userManager->get($userId))) {
$avatar = $this->avatarManager->getAvatar($userId);
$image = $avatar->get($size);
} else {
$image = null;
}
/*** MOD END ***/

if ($image instanceof \OCP\IImage) {
$resp = new DataDisplayResponse($image->data(),
Http::STATUS_OK,
['Content-Type' => $image->mimeType()]);
$resp->setETag(crc32($image->data()));
} else {
$user = $this->userManager->get($userId);
$userName = $user ? $user->getDisplayName() : '';
$resp = new DataResponse([
'data' => [
'displayname' => $userName,
],
]);
}

$resp->addHeader('Pragma', 'public');
$resp->cacheFor(0);
$resp->setLastModified(new \DateTime('now', new \DateTimeZone('GMT')));

return $resp;
}
```

**Comment by MorrisJobke** [comment]
This is currently not yet implemented - see https://github.com/owncloud/core/issues/14564 for the corresponding ticket to allow fetching avatars in an unauthenticated way.

**Comment by MorrisJobke** [comment]
@gig13 https://github.com/owncloud/core/pull/21811 <- this is the fix, but documents is not officially supported -> removing blue ticket

**Comment by scolebrook** [comment]
@MorrisJobke I wouldn't exactly call displaying an X as a fix. It stops the http error codes, but I agree with @jancborchardt. I think the generic letter avatar should be displayed. The little mod in my code above does that.

**Comment by MorrisJobke** [comment]
> @MorrisJobke I wouldn't exactly call displaying an X as a fix. It stops the http error codes, but I agree with @jancborchardt. I think the generic letter avatar should be displayed. The little mod in my code above does that.

I just fixed the failure case as a bug fix. The X is another story and has nothing to do with this bug. Can you open a issue in the core issue tracker, because it is related to the general avatar code. Thanks :)
