### ISSUE TITLE
Issue opening MS Word Files

### ISSUE THREAD

**Issue by Sanman96** [owncloud/documents#602]
### Steps to reproduce
1. Updated to ownCloud 8.2.1 (stable) (via apt-get)
2. Installed libreOffice
3. Enabled local under documents settings
4. Click on a file (odt works but .doc(x) does not)

### Expected behavior
Opens a text editor like I had working in previous versions

### Actual behavior
If opened via files the screen displays

    Loading/index.php/apps/documents/ajax/download.php?path=%2FChapter%206.docx&requesttoken=G2UiA0UwLi4BLlRiNBJAVT0ePHo8HjEEAxxwWRAc%3AC5ZVsztODG0SAUucGJS8iQCm2YGkTj...

If opened via documents 

    Opens a blank screen with the loading gif, java console says https://192.168.1.107/index.php/apps/documents/ajax/session/joinasuser/2341 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### Server configuration
**Operating system**: 
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

**Web server:** 
Apache2

**Database:** 
MySQL

**PHP version:**
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**ownCloud version:**
ownCloud 8.2.1 (stable)

**Updated from an older ownCloud or fresh install:**
Yes

**List of activated apps:**

Enabled:
  - activity: 2.1.3
  - documents: 0.10.2
  - encryption: 1.1.0
  - files: 1.2.0
  - files_locking:
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - mail: 0.2.1
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - calendar
  - contacts
  - external
  - files_external
  - notifications
  - user_external
  - user_ldap
  - user_webdavauth

**The content of config/config.php:**

Tried it with and without the last two preview lines

{
"system": {
        "instanceid": "ocbbmrmddrlu",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.107",
            "www.santichen.com",
            "santichen.com"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/192.168.1.107",
        "dbtype": "mysql",
        "version": "8.2.1.4",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "192.168.1.103",
        "mail_smtpport": "25",
        "mail_from_address": "ryan",
        "mail_domain": "santichen.com",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir "
    }
}

**Are you using external storage, if yes which one:** No

**Are you using encryption:** Yes

**Are you using an external user-backend, if yes which one:** Not yet

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

### Owncloud Log
>Error	PHP	Array to string conversion at /var/www/owncloud/lib/private/template/functions.php#36	2016-01-06T05:01:02+00:00
Error	PHP	Array to string conversion at /var/www/owncloud/lib/private/template/functions.php#36	2016-01-06T04:45:52+00:00
Error	PHP	Call to undefined function OCA\Documents\get_temp_dir() at /var/www/owncloud/apps/documents/lib/converter.php#53	2016-01-06T04:40:55+00:00
Error	PHP	Call to undefined function OCA\Documents\get_temp_dir() at /var/www/owncloud/apps/documents/lib/converter.php#53	2016-01-06T04:40:55+00:00
Error	PHP	Call to undefined function OCA\Documents\get_temp_dir() at /var/www/owncloud/apps/documents/lib/converter.php#53	2016-01-06T04:39:54+00:00
Error	PHP	Call to undefined function OCA\Documents\get_temp_dir() at /var/www/owncloud/apps/documents/lib/converter.php#53	2016-01-06T04:39:54+00:00
Error	PHP	Array to string conversion at /var/www/owncloud/lib/private/template/functions.php#36	2016-01-06T04:32:54+00:00
Error	PHP	Call to undefined function OCA\Documents\get_temp_dir() at /var/www/owncloud/apps/documents/lib/converter.php#53	2016-01-06T04:30:50+00:00
Error	PHP	Call to undefined function OCA\Documents\get_temp_dir() at /var/www/owncloud/apps/documents/lib/converter.php#53	2016-01-06T04:29:16+00:00
Error	PHP	Call to undefined function OCA\Documents\get_temp_dir() at /var/www/owncloud/apps/documents/lib/converter.php#53	2016-01-06T04:28:53+00:00
Error	PHP	Call to undefined function OCA\Documents\get_temp_dir() at /var/www/owncloud/apps/documents/lib/converter.php#53	2016-01-06T04:28:52+00:00
Error	PHP	Call to undefined function OCA\Documents\get_temp_dir() at /var/www/owncloud/apps/documents/lib/converter.php#53	2016-01-06T04:27:20+00:00
Error	PHP	Call to undefined function OCA\Documents\get_temp_dir() at /var/www/owncloud/apps/documents/lib/converter.php#53	2016-01-06T04:27:09+00:00

**Comment by RealRancor** [comment]
@Sanman96 

> documents: 0.10.2

You're running an Version of documents for oC 8.1 very likely not compatible with 8.2. Please update the documents app to the version 0.11.0 compatible with oC 8.2.

**Comment by Sanman96** [comment]
Thanks that worked!
