### ISSUE TITLE
Cannot find the Documents App in my fresh owncloud installation

### ISSUE THREAD

**Issue by RockScience** [owncloud/documents#604]
I am looking to enable the app, however it is not in any of the sidebar list shown in App screen (Multimedia/Productivity/Game/Tool). 
Is it normal that it is not pre-installed? Should I install it manually?

Note: I installed ownCloud 8.1 on my Synology NAS, through the synoCommunity package

**Comment by RealRancor** [comment]
https://github.com/owncloud/appstore-issues/issues/39#issuecomment-171120100

**Comment by RealRancor** [comment]
Ok, seems this is unrelated to https://github.com/owncloud/appstore-issues/issues/39

**Comment by VicDeo** [comment]
@RockScience Not related to the app itself in any manner.
Do you have a message like 
`'This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features.` at the admin page?

**Comment by RealRancor** [comment]
@VicDeo The app wasn't showing up at https://api.owncloud.com/v1/content/data?version=8x2x0x0&categories=922&approved=all (see https://github.com/owncloud/appstore-issues/issues/39#issuecomment-174620156) so it was app or appstore related. But this seems to be now fixed as the app is now there.

@RockScience Can you confirm?

**Comment by RockScience** [comment]
@RealRancor I need to check from home and I am currently travelling. I will revert back on that. 
Do I need to reinstall owncloud first?

**Comment by RockScience** [comment]
I confirm, this is now fixed. Thank you
