### ISSUE TITLE
The icon is grayed out on oC 9 with documents master

### ISSUE THREAD

**Issue by enoch85** [owncloud/documents#609]
**Server**
PHP 7
MySQL 5.6
Documents Master
Ubuntu Server 14.04 

![deepinscreenshot20160218235201](https://cloud.githubusercontent.com/assets/4511254/13160917/da49570e-d69a-11e5-8224-061d20d06f84.png)

**Comment by PVince81** [comment]
@enoch85 probably still happening in 9.0.0 ?

**Comment by PVince81** [comment]
Wait, I see a fix here https://github.com/owncloud/documents/issues/610

So it's likely fixed in 9.0.0, closing.

@enoch85 please reopen if it still happens in 9.0.0 and post the info requested in https://github.com/owncloud/documents/pull/610#issuecomment-190789810

**Comment by enoch85** [comment]
This is fixed, sorry that I forgot closing.
