### ISSUE TITLE
Unable to open docx, but doc okay

### ISSUE THREAD

**Issue by avoidik** [owncloud/documents#614]
Ubuntu 14.04 i686. Stable ownCloud from PPA (8.2.2). 
```
Starting a session failed. Reason: <path>.docx is application/octet-stream and is not supported by Documents app 
```
Any hints?

**Comment by avoidik** [comment]
Sorry, found this. Closing issue.
https://github.com/owncloud/apps/issues/125

**Comment by VicDeo** [comment]
@avoidik owncloud/apps#125 is not a solution. 
It looks like mime detection is broken. 
Check if the file `resources/config/mimetypemapping.dist.json` exists and readable.
