### ISSUE TITLE
Document offered for download, instead of for viewing, when browsing using Pretty URLs

### ISSUE THREAD

**Issue by josh4trunks** [owncloud/documents#625]
* OC - 9.0.0
* Documents - 0.12.0
* Webserver - NGINX
* Pretty URLs enabled (browse owncloud without /index.php)
* Webroot - /owncloud

If I click on "Example.odt" from the files view URL of `example.com/owncloud/apps/files/?dir=%2FDocuments` I am offered to download the file.
If I click on the same document from the files view URL of `example.com/owncloud/index.php/apps/files/?dir=%2FDocuments` I am shown a full-screen preview of the file as expected.

Log does show anything related

**Comment by josh4trunks** [comment]
If this should instead be reported to owncloud/core I can close this and open an Issue there.
If any more information / debugging is needed I am happy to do so.

**Comment by josh4trunks** [comment]
I have a feeling this is related to the `index.php/` here https://github.com/owncloud/documents/blob/45728e0141a77715813f80d07d7cfef5d02f130c/appinfo/app.php#L51
I'm guessing this should just be `if (preg_match('%apps/files(/.*)?%', $url)) {` now.

See this commit which enabled proper functioning with Pretty URLs in the gallery app
https://github.com/owncloud/gallery/commit/034d4d86cd7b0c9e764d031850fb12a650cbfd5d

**Comment by VicDeo** [comment]
@josh4trunks please test #628
