### ISSUE TITLE
Documents Index doesn't show previews

### ISSUE THREAD

**Issue by josh4trunks** [owncloud/documents#626]
OC - 9.0.0
Documents - 0.12.0
Webserver - NGINX
Log - Nothing relevant in the log

Have previews been removed from the documents index? `/index.php/apps/documents/index`
My page shows a bunch of the blue 'x-office-document.svg' icon instead of previews like it did in OC8.2.
Thumnail previews for ODT/DOC/DOCX files show in the files app as expected.

**Comment by VicDeo** [comment]
@josh4trunks and this should be addressed with https://github.com/owncloud/documents/issues/630
