### ISSUE TITLE
Cannot be installed on ownCloud 9.1

### ISSUE THREAD

**Issue by treuss** [owncloud/documents#656]
App cannot be installed on ownCloud 9.0 because the following preconditions are not met:
ownCloud 9.0 or lower is required.

**Comment by PVince81** [comment]
@VicDeo please update the requirements and make sure the app works in 9.1. thanks

**Comment by 0xFireball** [comment]
Can confirm

**Comment by ryannolan** [comment]
I solved the problem by having the analyze function in in lib/private/DependencyAnalyzer.php return true no matter what. This is a minor security issue however I believe there are going to be ongoing political issues between owncloud and nextcloud for the coming months and it would probably be good to switch to another service entirely.

**Comment by devmarxx** [comment]
I got it running in OC 9.1 by editing the file appinfo/info.xml after I unpacked the documents.zip to the apps folder on my Owncloud server. I just changed 

max-version

from 9.0 to 11.0

After that I could activate the app from my administrator account without any problems ...

**Comment by PVince81** [comment]
The correct way is to edit "info.xml", but that should be done in a PR to "master" and "stable9.1".

Glad to hear that the app works properly for you with 9.1 after that.

**Comment by cusco** [comment]
Hi, i just checked out and enabled on owncloud 9.1.0 and.. there are a few javascript errors such as /apps/files/js/jquery.iframe-transport.js not found

When I click share, it just starts spinning... and share.php has a blank response 


![image](https://cloud.githubusercontent.com/assets/2995711/17479887/15e503b8-5d6d-11e6-8227-081daaa293a6.png)

Its not yet totally compatible with 9.1 ?

**Comment by cusco** [comment]
OK, I've checked out branch stable9.1 instead (my bad) - no errors.

But share still does not work. share.php returns blank response and either share with user or share link, just stay with a spinning circle without any graphical change

**Comment by VicDeo** [comment]
@treuss the compatible version has been published at the appstore recently

**Comment by treuss** [comment]
Awesome @VicDeo !

**Comment by VicDeo** [comment]
Fixed with https://github.com/owncloud/documents/pull/659

**Comment by RealRancor** [comment]
@PVince81 @VicDeo It seems the Documents App is not offered for 9.1 Users:

https://api.owncloud.com/v1/content/data?version=9x1x0x0&categories=922&approved=all

Might be caused by the ``Maximum required   ownCloud 9.0`` at https://apps.owncloud.com/content/show.php/Documents?content=168711

**Comment by VicDeo** [comment]
@RealRancor thanks, fixed!

**Comment by RealRancor** [comment]
Thanks, showing up now :+1:
